services:
    nginx:
        image: nginx:latest
        container_name: reverse_proxy
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
        depends_on:
            - app

    app:
        build:
            context: ../
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        networks:
            - app-network

networks:
    app-network:
