name: Check
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          username: root
          host: ${{ secrets.HOST }}
          password: ${{ secrets.PASSWORD }}
          script: cd ./crtvweb && git pull && composer install && npm install && npm run build
#  tests:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 1
#
#      - name: Install PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: 8.2
#
#      - name: Install composer dependencies
#        run: composer install --no-scripts
#
#      - name: Install NPM dependencies
#        run: npm install
#
#      - name: Compile assets
#        run: npm run build
